version: '3.8'

services:
  backend:
    build: ../../backend
    image: ghcr.io/patiphatrattanosot/visit-home-backend:${TAG_NAME}
    container_name: backend_service
    working_dir: /app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app_network

  frontend:
    build: ../../frontend
    image: ghcr.io/patiphatrattanosot/visit-home-frontend:${TAG_NAME}
    container_name: frontend_service
    working_dir: /app
    ports:
      - "80:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge